theme: jekyll-theme-slate
title: Matt Ferrero 
description: Welcome to my personal site where I cover a little about myself and my tech projects! I frequently work in Engineering, Software/Systems Development,
Networking, and Security
future: true
timezone: EST
